# SPDX-FileCopyrightText: 2025 Ilya246
#
# SPDX-License-Identifier: MPL-2.0

- type: ghostRole
  id: VesselAICore
  name: ghost-role-information-vessel-core
  description: ghost-role-information-vessel-core-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainVessel
