# SPDX-FileCopyrightText: 2025 Ilya246
# SPDX-FileCopyrightText: 2025 KiraZen_
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: MPL-2.0

- type: ghostRole
  id: RedactedBorg
  name: ghost-role-information-redacted-borg
  description: ghost-role-information-redacted-borg-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: PlayerBorgRedacted
  whitelisted: true

- type: ghostRole
  id: RemnantAICore
  name: ghost-role-information-redacted-core
  description: ghost-role-information-redacted-core-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainRedacted
  whitelisted: true

- type: ghostRole
  id: TSFMCAICore
  name: ghost-role-information-tsfmc-core
  description: ghost-role-information-tsfmc-core-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainTSFMC
  whitelisted: true

- type: ghostRole
  id: RogueAICore
  name: ghost-role-information-rogue-core
  description: ghost-role-information-rogue-core-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainRogue
  whitelisted: true
