# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Qulibly
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 LukeZurg22
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 ScyronX
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: PirateBoatswain
  name: job-name-pirate-boatswain
  description: job-description-pirate-boatswain
  playTimeTracker: JobPirateBoatswain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours # mono
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 90000 # 25 hours
  startingGear: PirateBoatswainGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateBoatswain"
  supervisors: job-supervisors-pirate-boatswain
  weight: 30
  displayWeight: 30
  setPreference: true
  guides: [ BasicLore, PhaethonDynasty] # Mono
  access:
  - Pirate
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateBoatswainGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    #belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
    #pocket2: AppraisalTool
  storage:
    back:
    - RadioHandheldNF
