# SPDX-FileCopyrightText: 2023 Cheackraze
# SPDX-FileCopyrightText: 2023 LankLTE
# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 ErhardSteinhauer
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2025 Arcticular
# SPDX-FileCopyrightText: 2025 dustylens
# SPDX-FileCopyrightText: 2025 thoughtlessuser
#
# SPDX-License-Identifier: MPL-2.0

- type: playTimeTracker
  id: JobERTMailCarrier

- type: playTimeTracker
  id: JobMercenary

- type: playTimeTracker
  id: JobPilot

- type: playTimeTracker
  id: JobPublicAffairsLiaison

- type: playTimeTracker
  id: JobSecurityGuard

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobStc

- type: playTimeTracker
  id: JobPirateCaptain

- type: playTimeTracker
  id: JobPirateFirstMate

- type: playTimeTracker
  id: JobPirate

- type: playTimeTracker
  id: JobPDVInfiltrator

- type: playTimeTracker
  id: JobPDVDenasvar

- type: playTimeTracker
  id: JobDirectorOfCare
