# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 ike709
# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2022 wrexbe
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 SlamBamActionman
# SPDX-FileCopyrightText: 2024 TsjipTsjip
# SPDX-FileCopyrightText: 2025 Aiden
# SPDX-FileCopyrightText: 2025 Redrover1760
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Check Merge Conflicts

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Label:
    if: ( github.event.pull_request.draft == false )
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: eps1lon/actions-label-merge-conflict@v3.0.0
        with:
          dirtyLabel: "S: Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
