# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 SlamBamActionman
# SPDX-FileCopyrightText: 2025 Aiden
#
# SPDX-License-Identifier: MPL-2.0

name: "Labels: Branch stable"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'stable'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Branch: Stable"
