# SPDX-FileCopyrightText: 2022 Paul Ritter
# SPDX-FileCopyrightText: 2022 wrexbe
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Moony
# SPDX-FileCopyrightText: 2023 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Myra
# SPDX-FileCopyrightText: 2025 Aiden
# SPDX-FileCopyrightText: 2025 Coenx-flex
# SPDX-FileCopyrightText: 2025 Cojoke
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: RGA schema validator
on:
  push:
    branches: [ main, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yaml-schema-validation:
    name: YAML RGA schema validator
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'FrontierATC' # Frontier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup Submodule
      run: git submodule update --init
    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5
    - uses: PaulRitter/yaml-schema-validator@v1
      with:
        schema: .github/Schemas/rga.yml
        path_pattern: .*attributions.ya?ml$
        validators_path: .github/Schemas/rga_validators.py
        validators_requirements: .github/Schemas/rga_requirements.txt
